job-android:

  stage: build

  script:
    - ./gradlew app:dependencies | grep org.linphone
    - ./gradlew assembleDebug
    - cp ./app/build/outputs/apk/debug/app-debug.apk lindoor-debug-unsigned.apk

  artifacts:
    paths:
      - lindoor-debug-unsigned.apk 
    when: always
    expire_in: 1 week

